updated build recipes

diff --git a/swig_wrappers/build_recipes/linux/Dockerfile_linux_x86_64 b/swig_wrappers/build_recipes/linux/Dockerfile_linux_x86_64
--- a/swig_wrappers/build_recipes/linux/Dockerfile_linux_x86_64
+++ b/swig_wrappers/build_recipes/linux/Dockerfile_linux_x86_64
@@ -5,8 +5,10 @@ ARG DEPS="/deps"
 ARG WORK="/work"
 ARG SRC="/src"
 ARG IMAGE="/image"
-ARG RDKIT_RELEASE="2022_09_3"
-ARG RDKIT_CHKSUM="1c2df38b2578cebadb64cc76753a6e5c"
+# ARG RDKIT_RELEASE="2022_09_3"
+# ARG RDKIT_CHKSUM="1c2df38b2578cebadb64cc76753a6e5c"
+ARG RDKIT_GIT_URL="https://github.com/rdkit/rdkit"
+ARG RDKIT_BRANCH="master"
 
 FROM centos:7 AS build-stage
 ARG ARCH
@@ -16,6 +18,8 @@ ARG SRC
 ARG IMAGE
 ARG RDKIT_RELEASE
 ARG RDKIT_CHKSUM
+ARG RDKIT_GIT_URL
+ARG RDKIT_BRANCH
 
 USER root
 
@@ -44,7 +48,7 @@ ARG DEVTOOLSET_PATH="/opt/rh/devtoolset-11"
 
 RUN yum update -y
 RUN yum install -y centos-release-scl
-RUN yum install -y devtoolset-11 bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel patch
+RUN yum install -y devtoolset-11 bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel patch git
 
 RUN curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo
 RUN yum install -y mono-devel
@@ -171,36 +175,33 @@ RUN source ${DEVTOOLSET_PATH}/enable && CC="gcc -fPIC" CXX="g++ -fPIC" \
 RUN source ${DEVTOOLSET_PATH}/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
 WORKDIR ${SRC}
-RUN curl -L -O https://github.com/rdkit/rdkit/archive/refs/tags/Release_${RDKIT_RELEASE}.tar.gz && \
-    [ `md5sum Release_${RDKIT_RELEASE}.tar.gz | awk '{print $1}'` = ${RDKIT_CHKSUM} ] || \
-    ( >&2 echo "Failed to download RDKit" && exit 1 )
-RUN tar xzf Release_${RDKIT_RELEASE}.tar.gz
-WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}
-RUN sed -i "s|#if _MSC_VER|#ifdef _WIN32|" Code/GraphMol/catch_chirality.cpp
-RUN sed -i "s|Windows\.h|windows.h|" Code/GraphMol/MMPA/MMPA_UnitTest.cpp
+RUN if [ -n "${RDKIT_RELEASE}" ]; then \
+        curl -L -O ${RDKIT_GIT_URL}/archive/refs/tags/Release_${RDKIT_RELEASE}.tar.gz && \
+            [ `md5sum Release_${RDKIT_RELEASE}.tar.gz | awk '{print $1}'` = ${RDKIT_CHKSUM} ] || \
+            ( >&2 echo "Failed to download RDKit" && exit 1 ); \
+        tar xzf Release_${RDKIT_RELEASE}.tar.gz && \
+        ln -s rdkit-Release_${RDKIT_RELEASE} rdkit; \
+    else \
+        git clone ${RDKIT_GIT_URL}.git && cd rdkit && git checkout ${RDKIT_BRANCH}; \
+    fi
+WORKDIR ${SRC}/rdkit
 RUN sed -i -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC ${DEPS}/include/cairo)\n\1\2 ${DEPS}/lib/libcairo.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
     -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(.*\)\()\)|\1\2\3 ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a\4|" \
     Code/GraphMol/MolDraw2D/CMakeLists.txt
+RUN sed -i "s|^\( *set(RDKit_SERIALIZATION_LIBS *\${Boost_SERIALIZATION_LIBRARY}\)\()\)|\1 ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a\2|" \
+    Code/GraphMol/ChemReactions/CMakeLists.txt
 RUN sed -i -e "s|if(WIN32)|if(FALSE)|" \
     -e "s|SWIG_LINK_LIBRARIES|set(RDKit_Wrapper_Libs \"-Wl,--no-undefined;\${RDKit_Wrapper_Libs};${DEPS}/lib/libcairo.a;${DEPS}/lib/libpixman-1.a;${DEPS}/lib/libpng16.a;${DEPS}/lib/libz.a;${DEPS}/lib/libbz2.a\")\n&|" \
     Code/JavaWrappers/gmwrapper/CMakeLists.txt
 RUN sed -i "s|SWIG_LINK_LIBRARIES|set(RDKit_Wrapper_Libs \"-Wl,--no-undefined;\${RDKit_Wrapper_Libs};${DEPS}/lib/libcairo.a;${DEPS}/lib/libpixman-1.a;${DEPS}/lib/libpng16.a;${DEPS}/lib/libz.a;${DEPS}/lib/libbz2.a\")\n&|" \
     Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
 
-# Patch for Avalon 2.0.4a
-RUN sed -i -e "s|set(AVALON_VERSION \"2\.0\.2\")|set(AVALON_VERSION \"2.0.4a\")|" \
-    -e "s|set(AVALONTOOLS_MD5SUM \"fc188383a8896802e948c977b73dbe71\")|set(AVALONTOOLS_MD5SUM \"8e0fdedce0d93bdbc1e3c6ab3ae5c6cf\")|" \
-    -e "s|if(CMAKE_C_COMPILER_ID STREQUAL \"GNU\")|set(reaccsio_c \"\${AVALONTOOLS_DIR}/src/main/C/common/reaccsio.c\")\nfile(READ \${reaccsio_c} reaccsio_c_data)\nif (NOT \"\${reaccsio_c_data}\" MATCHES \"fputc('\\\\\\\\\\\\\\\\0')\")\n    string(REGEX REPLACE \"( *)(int)( *)(Size;)\" \"\\\\\\\\1\\\\\\\\2\\\\\\\\3\\\\\\\\4\\\\\\\\n\\\\\\\\1int\\\\\\\\3Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(Size \\\\\\\\+= strlen\\\\\\\\(Line\\\\\\\\);)\" \"\\\\\\\\1Len = strlen(Line);\\\\\\\\n\\\\\\\\1if (!Len) break;\\\\\\\\n\\\\\\\\1Size += Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"(bufsize = 5\\\\\\\\*80 \\\\\\\\+ mp->n_atoms\\\\\\\\*80 \\\\\\\\+ mp->n_bonds\\\\\\\\*80 \\\\\\\\+ mp->n_props\\\\\\\\*80)(;)\" \"\\\\\\\\1 + 1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(rewind\\\\\\\\(fp\\\\\\\\);)\" \"\\\\\\\\1fputc('\\\\\\\\\\\\\\\\0', fp);\\\\\\\\n\\\\\\\\1fflush(fp);\\\\\\\\n\\\\\\\\1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    file(WRITE \${reaccsio_c} \"\${reaccsio_c_data}\")\nendif()\n\n&|" \
-    External/AvalonTools/CMakeLists.txt
-RUN sed -i -e "s|\(optBuffer\[optString\.size()\)\( - 1\)\(\] = '\\\\n';\)|\1\3|" \
-    -e "s|\(optBuffer\[optString.size()\)\(\]\)\( = '\\\\0';\)|\1 + 1\2\3|" External/AvalonTools/AvalonTools.cpp
-
 # Patch for SWIG loggers
 RUN sed -i "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/gmwrapper/GraphMolJava.i
 RUN sed -i "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
 
 RUN mkdir build
-WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}/build
+WORKDIR ${SRC}/rdkit/build
 RUN source ${DEVTOOLSET_PATH}/enable && FREETYPE_DIR=${DEPS} ${DEPS}/bin/cmake \
     -D RDK_BUILD_INCHI_SUPPORT=ON \
     -D RDK_BUILD_AVALON_SUPPORT=ON \
@@ -233,14 +234,14 @@ RUN source ${DEVTOOLSET_PATH}/enable && FREETYPE_DIR=${DEPS} ${DEPS}/bin/cmake \
     -D CMAKE_INSTALL_PREFIX=${IMAGE} \
     ..
 RUN source ${DEVTOOLSET_PATH}/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
-RUN RDBASE=${SRC}/rdkit-Release_${RDKIT_RELEASE} ${DEPS}/bin/ctest
+RUN RDBASE=${SRC}/rdkit ${DEPS}/bin/ctest
 
 FROM scratch as export-stage
 ARG ARCH
 ARG SRC
 ARG RDKIT_RELEASE
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKit.jar /${ARCH}/org.RDKit.jar
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKitDoc.jar /${ARCH}/org.RDKitDoc.jar
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/libGraphMolWrap.so /${ARCH}/libGraphMolWrap.so
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKFuncs.so /${ARCH}/RDKFuncs.so
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll /${ARCH}/RDKit2DotNet.dll
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/org.RDKit.jar /${ARCH}/org.RDKit.jar
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/org.RDKitDoc.jar /${ARCH}/org.RDKitDoc.jar
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/libGraphMolWrap.so /${ARCH}/libGraphMolWrap.so
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/csharp_wrapper/RDKFuncs.so /${ARCH}/RDKFuncs.so
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll /${ARCH}/RDKit2DotNet.dll
diff --git a/swig_wrappers/build_recipes/macos/Ansible_playbook_macOS.yml b/swig_wrappers/build_recipes/macos/Ansible_playbook_macOS.yml
--- a/swig_wrappers/build_recipes/macos/Ansible_playbook_macOS.yml
+++ b/swig_wrappers/build_recipes/macos/Ansible_playbook_macOS.yml
@@ -11,6 +11,8 @@
     BUILD_TARGET: "-mmacosx-version-min={{ MIN_MACOS_VERSION }} -arch {{ ARCH }}"
     RDKIT_RELEASE: "2022_09_3"
     RDKIT_CHKSUM: "1c2df38b2578cebadb64cc76753a6e5c"
+    RDKIT_GIT_URL: "https://github.com/rdkit/rdkit"
+    RDKIT_BRANCH: "master"
     PKGCONFIG_VERSION: "0.29.2"
     PKGCONFIG_CHECKSUM: "76e501663b29cb7580245720edfb6106164fad2b"
     ZLIB_VERSION: "1.2.13"
@@ -618,27 +620,30 @@
   - name: install RDKit
     block:
     - name: download RDKit
-      ansible.builtin.shell: if [ ! -e "Release_{{ RDKIT_RELEASE }}.tar.gz" ] || \
-          [ `md5 -q "Release_{{ RDKIT_RELEASE }}.tar.gz"` != {{ RDKIT_CHKSUM }} ]; then \
-          rm -f "Release_{{ RDKIT_RELEASE }}.tar.gz"; \
-          curl -L -O "https://github.com/rdkit/rdkit/archive/refs/tags/Release_{{ RDKIT_RELEASE }}.tar.gz" && \
-            [ `md5 -q "Release_{{ RDKIT_RELEASE }}.tar.gz"` = {{ RDKIT_CHKSUM }} ] || \
-            ( >&2 echo "Failed to download RDKit" && exit 1 ); \
+      ansible.builtin.shell: if [ -n "${RDKIT_RELEASE}" ]; then \
+          if [ ! -e "Release_{{ RDKIT_RELEASE }}.tar.gz" ] || \
+            [ `md5 -q "Release_{{ RDKIT_RELEASE }}.tar.gz"` != {{ RDKIT_CHKSUM }} ]; then \
+            rm -f "Release_{{ RDKIT_RELEASE }}.tar.gz"; \
+            curl -L -O "{{ RDKIT_GIT_URL }}/archive/refs/tags/Release_{{ RDKIT_RELEASE }}.tar.gz" && \
+              [ `md5 -q "Release_{{ RDKIT_RELEASE }}.tar.gz"` = {{ RDKIT_CHKSUM }} ] || \
+              ( >&2 echo "Failed to download RDKit" && exit 1 ); \
+          fi \
+          tar xzf "Release_{{ RDKIT_RELEASE }}.tar.gz" && \
+          rm -f rdkit && \
+          ln -s rdkit-Release_${RDKIT_RELEASE} rdkit; \
+        else \
+          git clone "{{ RDKIT_GIT_URL }}.git" && cd rdkit && git checkout "{{ RDKIT_BRANCH }}"; \
         fi
       args:
         chdir: "{{ SRC }}"
 
-    - name: untar RDKit
-      ansible.builtin.shell: tar xzf "Release_{{ RDKIT_RELEASE }}.tar.gz"
-      args:
-        chdir: "{{ SRC }}"
-
     - name: patch RDKit
-      ansible.builtin.shell: sed -i ".orig" "s|#if _MSC_VER|#ifdef _WIN32|" Code/GraphMol/catch_chirality.cpp && \
-        sed -i ".orig" "s|Windows\.h|windows.h|" Code/GraphMol/MMPA/MMPA_UnitTest.cpp && \
-        sed -i ".orig" -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC {{ DEPS }}/include/cairo)\n\1\2 {{ DEPS }}/lib/libcairo.a {{ DEPS }}/lib/libpixman-1.a {{ DEPS }}/lib/libpng16.a \"-framework CoreFoundation\" \"-framework CoreGraphics\"|" \
+      ansible.builtin.shell: sed -i ".orig" \
+          -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC {{ DEPS }}/include/cairo)\n\1\2 {{ DEPS }}/lib/libcairo.a {{ DEPS }}/lib/libpixman-1.a {{ DEPS }}/lib/libpng16.a \"-framework CoreFoundation\" \"-framework CoreGraphics\"|" \
           -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(.*\)\()\)|\1\2\3 {{ DEPS }}/lib/libz.a {{ DEPS }}/lib/libbz2.a\4|" \
           Code/GraphMol/MolDraw2D/CMakeLists.txt && \
+        sed -i ".orig" "s|^\( *set(RDKit_SERIALIZATION_LIBS *\${Boost_SERIALIZATION_LIBRARY}\)\()\)|\1 {{ DEPS }}/lib/libz.a {{ DEPS }}/lib/libbz2.a\2|" \
+            Code/GraphMol/ChemReactions/CMakeLists.txt && \
         sed -i ".orig" -e "s|if(WIN32)|if(FALSE)|" \
           -e "s|\(SWIG_LINK_LIBRARIES *( *\)\(GraphMolWrap *\)\(\${RDKit_Wrapper_Libs}\)|set(RDKit_Wrapper_Libs \"-Wl,-undefined,error;\${RDKit_Wrapper_Libs};{{ DEPS }}/lib/libcairo.a;{{ DEPS }}/lib/libpixman-1.a;{{ DEPS }}/lib/libpng16.a;{{ DEPS }}/lib/libz.a;{{ DEPS }}/lib/libbz2.a\")\n\1\2\3 \"-framework CoreFoundation\" \"-framework CoreGraphics\"|" \
           Code/JavaWrappers/gmwrapper/CMakeLists.txt && \
@@ -647,22 +652,12 @@
         sed -i ".orig" "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/gmwrapper/GraphMolJava.i && \
         sed -i ".orig" "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}"
-
-    - name: update Avalon to 2.0.4a
-      ansible.builtin.shell: sed -i ".orig" -e "s|set(AVALON_VERSION \"2\.0\.2\")|set(AVALON_VERSION \"2.0.4a\")|" \
-        -e "s|set(AVALONTOOLS_MD5SUM \"fc188383a8896802e948c977b73dbe71\")|set(AVALONTOOLS_MD5SUM \"8e0fdedce0d93bdbc1e3c6ab3ae5c6cf\")|" \
-        -e "s|if(CMAKE_C_COMPILER_ID STREQUAL \"GNU\")|set(reaccsio_c \"\${AVALONTOOLS_DIR}/src/main/C/common/reaccsio.c\")\nfile(READ \${reaccsio_c} reaccsio_c_data)\nif (NOT \"\${reaccsio_c_data}\" MATCHES \"fputc('\\\\\\\\\\\\\\\\0')\")\n    string(REGEX REPLACE \"( *)(int)( *)(Size;)\" \"\\\\\\\\1\\\\\\\\2\\\\\\\\3\\\\\\\\4\\\\\\\\n\\\\\\\\1int\\\\\\\\3Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(Size \\\\\\\\+= strlen\\\\\\\\(Line\\\\\\\\);)\" \"\\\\\\\\1Len = strlen(Line);\\\\\\\\n\\\\\\\\1if (!Len) break;\\\\\\\\n\\\\\\\\1Size += Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"(bufsize = 5\\\\\\\\*80 \\\\\\\\+ mp->n_atoms\\\\\\\\*80 \\\\\\\\+ mp->n_bonds\\\\\\\\*80 \\\\\\\\+ mp->n_props\\\\\\\\*80)(;)\" \"\\\\\\\\1 + 1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(rewind\\\\\\\\(fp\\\\\\\\);)\" \"\\\\\\\\1fputc('\\\\\\\\\\\\\\\\0', fp);\\\\\\\\n\\\\\\\\1fflush(fp);\\\\\\\\n\\\\\\\\1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    file(WRITE \${reaccsio_c} \"\${reaccsio_c_data}\")\nendif()\n\n&|" \
-        External/AvalonTools/CMakeLists.txt && \
-        sed -i ".orig" -e "s|\(optBuffer\[optString\.size()\)\( - 1\)\(\] = '\\\\n';\)|\1\3|" \
-        -e "s|\(optBuffer\[optString.size()\)\(\]\)\( = '\\\\0';\)|\1 + 1\2\3|" External/AvalonTools/AvalonTools.cpp
-      args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}"
+        chdir: "{{ SRC }}/rdkit"
 
     - name: create build sub-directory
       ansible.builtin.shell: mkdir -p build
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}"
+        chdir: "{{ SRC }}/rdkit"
 
     - name: configure RDKit
       ansible.builtin.shell: rm -f CMakeCache.txt && \
@@ -703,24 +698,24 @@
           -D CMAKE_OSX_ARCHITECTURES="{{ ARCH }}" \
           ..
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}/build"
+        chdir: "{{ SRC }}/rdkit/build"
 
     - name: build RDKit
       ansible.builtin.shell: make -j{{ BUILD_CONCURRENCY }} clean && \
         make -j{{ BUILD_CONCURRENCY }} && make -j{{ BUILD_CONCURRENCY }} install
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}/build"
+        chdir: "{{ SRC }}/rdkit/build"
 
     - name: test RDKit
       ansible.builtin.shell: export JAVA_ARCH=`echo {{ ARCH }} | sed "s|arm64|aarch64|"` && \
         export JAVA_HOME="`ls -d /Applications/KNIME_*_${JAVA_ARCH}.app/Contents/Eclipse/plugins/org.knime.binary.jre.macosx.${JAVA_ARCH}_*/jre/Contents/Home`" && \
-        RDBASE="{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}" PATH="$JAVA_HOME/bin:$PATH" "{{ DEPS }}/bin/ctest"
+        RDBASE="{{ SRC }}/rdkit" PATH="$JAVA_HOME/bin:$PATH" "{{ DEPS }}/bin/ctest"
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}/build"
+        chdir: "{{ SRC }}/rdkit/build"
 
     - name: copy RDKit libraries
       ansible.builtin.shell: cp Code/JavaWrappers/gmwrapper/libGraphMolWrap.jnilib Code/JavaWrappers/gmwrapper/org.RDKit*.jar {{ IMAGE }} && \
         cp Code/JavaWrappers/csharp_wrapper/RDKFuncs.so Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll {{ IMAGE }}
       args:
-        chdir: "{{ SRC }}/rdkit-Release_{{ RDKIT_RELEASE }}"
+        chdir: "{{ SRC }}/rdkit"
     when: libGraphMolWrap.stat.exists == false
diff --git a/swig_wrappers/build_recipes/windows/Dockerfile_windows b/swig_wrappers/build_recipes/windows/Dockerfile_windows
--- a/swig_wrappers/build_recipes/windows/Dockerfile_windows
+++ b/swig_wrappers/build_recipes/windows/Dockerfile_windows
@@ -6,8 +6,10 @@ ARG DEPS="/deps"
 ARG WORK="/work"
 ARG SRC="/src"
 ARG IMAGE="/image"
-ARG RDKIT_RELEASE="2022_09_3"
-ARG RDKIT_CHKSUM="1c2df38b2578cebadb64cc76753a6e5c"
+# ARG RDKIT_RELEASE="2022_09_3"
+# ARG RDKIT_CHKSUM="1c2df38b2578cebadb64cc76753a6e5c"
+ARG RDKIT_GIT_URL="https://github.com/rdkit/rdkit"
+ARG RDKIT_BRANCH="master"
 
 FROM fedora:36 AS build-stage-prep
 ARG ARCH
@@ -15,6 +17,10 @@ ARG DEPS
 ARG WORK
 ARG SRC
 ARG IMAGE
+ARG RDKIT_RELEASE
+ARG RDKIT_CHKSUM
+ARG RDKIT_GIT_URL
+ARG RDKIT_BRANCH
 
 RUN echo "Building Windows ${ARCH} Java and C# DLLs"
 RUN [ "${ARCH}" = x86_64 ] || [ "${ARCH}" = i686 ] || \
@@ -24,7 +30,7 @@ USER root
 
 RUN dnf update -y
 RUN dnf install -y patch bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel \
-    mono-devel make gcc gcc-c++
+    mono-devel make gcc gcc-c++ git
 
 RUN groupadd -g 1005 docker && \
     useradd -u 1005 -s /bin/bash -g docker docker && \
@@ -59,6 +65,8 @@ ARG IMAGE
 ARG BUILD_CONCURRENCY="6"
 ARG RDKIT_RELEASE
 ARG RDKIT_CHKSUM
+ARG RDKIT_GIT_URL
+ARG RDKIT_BRANCH
 ARG ZLIB_VERSION="1.2.13"
 ARG ZLIB_CHKSUM="9b8aa094c4e5765dabf4da391f00d15c"
 ARG BZIP2_VERSION="1.0.8"
@@ -205,29 +213,26 @@ RUN CC="${ARCH}-w64-mingw32-gcc -fPIC -I${DEPS}/include" \
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
 WORKDIR ${SRC}
-RUN curl -L -O https://github.com/rdkit/rdkit/archive/refs/tags/Release_${RDKIT_RELEASE}.tar.gz && \
-    [ `md5sum Release_${RDKIT_RELEASE}.tar.gz | awk '{print $1}'` = ${RDKIT_CHKSUM} ] || \
-    ( >&2 echo "Failed to download RDKit" && exit 1 )
-RUN tar xzf Release_${RDKIT_RELEASE}.tar.gz
-WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}
-RUN sed -i "s|#if _MSC_VER|#ifdef _WIN32|" Code/GraphMol/catch_chirality.cpp
-RUN sed -i "s|Windows\.h|windows.h|" Code/GraphMol/MMPA/MMPA_UnitTest.cpp
+RUN if [ -n "${RDKIT_RELEASE}" ]; then \
+        curl -L -O ${RDKIT_GIT_URL}/archive/refs/tags/Release_${RDKIT_RELEASE}.tar.gz && \
+            [ `md5sum Release_${RDKIT_RELEASE}.tar.gz | awk '{print $1}'` = ${RDKIT_CHKSUM} ] || \
+            ( >&2 echo "Failed to download RDKit" && exit 1 ); \
+        tar xzf Release_${RDKIT_RELEASE}.tar.gz && \
+        ln -s rdkit-Release_${RDKIT_RELEASE} rdkit; \
+    else \
+        git clone ${RDKIT_GIT_URL}.git && cd rdkit && git checkout ${RDKIT_BRANCH}; \
+    fi
+WORKDIR ${SRC}/rdkit
 RUN sed -i -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC ${DEPS}/include/cairo)\n\1\2 ${DEPS}/lib/libcairo.a /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
     -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(.*\)\()\)|\1\2\3 ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a\4|" \
     Code/GraphMol/MolDraw2D/CMakeLists.txt
+RUN sed -i "s|^\( *set(RDKit_SERIALIZATION_LIBS *\${Boost_SERIALIZATION_LIBRARY}\)\()\)|\1 ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a\2|" \
+    Code/GraphMol/ChemReactions/CMakeLists.txt
 RUN sed -i -e "s|if(WIN32)|if(FALSE)|" \
     -e "s|\(SWIG_LINK_LIBRARIES *( *\)\(GraphMolWrap *\)\(\${RDKit_Wrapper_Libs}\)|set(RDKit_Wrapper_Libs \"-Wl,--no-undefined;\${RDKit_Wrapper_Libs};${DEPS}/lib/libcairo.a;${DEPS}/lib/libpixman-1.a;${DEPS}/lib/libpng16.a;${DEPS}/lib/libz.a;${DEPS}/lib/libbz2.a\")\n\1\2-static -static-libgcc -static-libstdc++ ${SWIG_STDCALL_SWITCH} \3 /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a|" \
     Code/JavaWrappers/gmwrapper/CMakeLists.txt
 RUN sed -i "s|\(SWIG_LINK_LIBRARIES *( *\)\(RDKFuncs *\)\(\${RDKit_Wrapper_Libs}\)|set(RDKit_Wrapper_Libs \"-Wl,--no-undefined;\${RDKit_Wrapper_Libs};${DEPS}/lib/libcairo.a;${DEPS}/lib/libpixman-1.a;${DEPS}/lib/libpng16.a;${DEPS}/lib/libz.a;${DEPS}/lib/libbz2.a\")\n\1\2-static -static-libgcc -static-libstdc++ ${SWIG_STDCALL_SWITCH} \3 /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a|" \
     Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
-
-# Patch for Avalon 2.0.4a
-RUN sed -i -e "s|set(AVALON_VERSION \"2\.0\.2\")|set(AVALON_VERSION \"2.0.4a\")|" \
-    -e "s|set(AVALONTOOLS_MD5SUM \"fc188383a8896802e948c977b73dbe71\")|set(AVALONTOOLS_MD5SUM \"8e0fdedce0d93bdbc1e3c6ab3ae5c6cf\")|" \
-    -e "s|if(CMAKE_C_COMPILER_ID STREQUAL \"GNU\")|set(reaccsio_c \"\${AVALONTOOLS_DIR}/src/main/C/common/reaccsio.c\")\nfile(READ \${reaccsio_c} reaccsio_c_data)\nif (NOT \"\${reaccsio_c_data}\" MATCHES \"fputc('\\\\\\\\\\\\\\\\0')\")\n    string(REGEX REPLACE \"( *)(int)( *)(Size;)\" \"\\\\\\\\1\\\\\\\\2\\\\\\\\3\\\\\\\\4\\\\\\\\n\\\\\\\\1int\\\\\\\\3Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(Size \\\\\\\\+= strlen\\\\\\\\(Line\\\\\\\\);)\" \"\\\\\\\\1Len = strlen(Line);\\\\\\\\n\\\\\\\\1if (!Len) break;\\\\\\\\n\\\\\\\\1Size += Len;\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"(bufsize = 5\\\\\\\\*80 \\\\\\\\+ mp->n_atoms\\\\\\\\*80 \\\\\\\\+ mp->n_bonds\\\\\\\\*80 \\\\\\\\+ mp->n_props\\\\\\\\*80)(;)\" \"\\\\\\\\1 + 1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    string(REGEX REPLACE \"( *)(rewind\\\\\\\\(fp\\\\\\\\);)\" \"\\\\\\\\1fputc('\\\\\\\\\\\\\\\\0', fp);\\\\\\\\n\\\\\\\\1fflush(fp);\\\\\\\\n\\\\\\\\1\\\\\\\\2\" reaccsio_c_data \"\${reaccsio_c_data}\")\n    file(WRITE \${reaccsio_c} \"\${reaccsio_c_data}\")\nendif()\n\n&|" \
-    External/AvalonTools/CMakeLists.txt
-RUN sed -i -e "s|\(optBuffer\[optString\.size()\)\( - 1\)\(\] = '\\\\n';\)|\1\3|" \
-    -e "s|\(optBuffer\[optString.size()\)\(\]\)\( = '\\\\0';\)|\1 + 1\2\3|" External/AvalonTools/AvalonTools.cpp
 
 # Patch for SWIG loggers
 RUN sed -i "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/gmwrapper/GraphMolJava.i
@@ -249,7 +254,7 @@ RUN echo > win-${ARCH}.cmake -e \
     "set(CMAKE_CROSS_COMPILING TRUE)\n"
 
 RUN mkdir build
-WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}/build
+WORKDIR ${SRC}/rdkit/build
 RUN export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk && \
     FREETYPE_DIR=${DEPS} ${DEPS}/bin/cmake \
     -D RDK_BUILD_INCHI_SUPPORT=ON \
@@ -302,9 +307,9 @@ FROM scratch as export-stage
 ARG ARCH
 ARG SRC
 ARG RDKIT_RELEASE
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKit.jar /${ARCH}/org.RDKit.jar
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKitDoc.jar /${ARCH}/org.RDKitDoc.jar
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/GraphMolWrap.dll /${ARCH}/GraphMolWrap.dll
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKFuncs.dll /${ARCH}/RDKFuncs.dll
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll /${ARCH}/RDKit2DotNet.dll
-COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/build/windows_ctest_exe.tar.bz2 /${ARCH}/windows_ctest_exe.tar.bz2
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/org.RDKit.jar /${ARCH}/org.RDKit.jar
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/org.RDKitDoc.jar /${ARCH}/org.RDKitDoc.jar
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/gmwrapper/GraphMolWrap.dll /${ARCH}/GraphMolWrap.dll
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/csharp_wrapper/RDKFuncs.dll /${ARCH}/RDKFuncs.dll
+COPY --from=build-stage ${SRC}/rdkit/Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll /${ARCH}/RDKit2DotNet.dll
+COPY --from=build-stage ${SRC}/rdkit/build/windows_ctest_exe.tar.bz2 /${ARCH}/windows_ctest_exe.tar.bz2
